### ISSUE TITLE
SHA256 mismatch after the bundle is downloaded

### ISSUE THREAD

**Issue by nikoladev** [ran-dall/homebrew-pnpm#1]
When trying the formula I get an SHA256 mismatch after the bundle is downloaded:

```shell
==> Installing pnpm
==> Downloading https://registry.npmjs.org/@pnpm/bundled/-/bundled-1.23.2.tgz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 5b3a6fbce64f2e1e45e44ddbf0836226794c9a78d114a35a413ca9bb1ee1c41a
Actual: 5440381d6084fa15cba116ddd72666177e5702b9bbacc009db5c39cc860c19f4
```

**Comment by ran-dall** [comment]
Sorry, didn't see the issue till today. I haven't updated the formulae in a minute. I'll update it today to the latest version and also fix the hash mismatch.

**Comment by nikoladev** [comment]
Great, thanks :)

**Comment by zkochan** [comment]
@nikoladev if you could confirm that it works, we can probably move it to the pnpm repo and automate somehow. To always have an up-to-date homebrew package

**Comment by ran-dall** [comment]
@zkochan I already merged a pull request that fixed the initial problem. I would agree with you though that finding a way to keep it up to date though without having to manually do it each time would be nice though.

**Comment by nikoladev** [comment]
@ran-dall @zkochan That PR fixed the issue!
